apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-deployment
  labels:
    app: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
        - name: question-service
          image: gcr.io/cs3219-peerprep-440616/question-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_URI
                  name: question-service-config
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: ENV
                  name: question-service-config
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: default
spec:
  selector:
    app: question-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
