apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: gcr.io/cs3219-peerprep-440616/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: DB_LOCAL_URI
              valueFrom:
                configMapKeyRef:
                  key: DB_LOCAL_URI
                  name: user-service-config
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: PORT
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: ENV
          resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
  loadBalancerIP: "34.143.154.218" # Reserved static IP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
