apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: default
type: Opaque
data:
  DB_CLOUD_URI: "<CONNECTION_STRING>"
  JWT_SECRET: "you-can-replace-this-with-your-own-secret"
  SENDGRID_API_KEY: "<SENDGRID_API_KEY>"
