apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: gcr.io/cs3219-peerprep-440616/frontend-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: VITE_FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-service-secrets
                  key: VITE_FIREBASE_API_KEY
            - name: VITE_FIREBASE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_FIREBASE_AUTH_DOMAIN
            - name: VITE_FIREBASE_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_FIREBASE_DATABASE_URL
            - name: VITE_FIREBASE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_FIREBASE_PROJECT_ID
            - name: VITE_FIREBASE_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_FIREBASE_STORAGE_BUCKET
            - name: VITE_FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_FIREBASE_MESSAGING_SENDER_ID
            - name: VITE_FIREBASE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_FIREBASE_APP_ID
            - name: VITE_FIREBASE_MEASUREMENT_ID
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_FIREBASE_MEASUREMENT_ID
            - name: VITE_USER_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_USER_SERVICE_API_URL
            - name: VITE_QUESTION_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_QUESTION_SERVICE_API_URL
            - name: VITE_REQUEST_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_REQUEST_SERVICE_API_URL
            - name: VITE_MATCHER_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_MATCHER_SERVICE_API_URL
            - name: VITE_COLLABORATION_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_COLLABORATION_SERVICE_API_URL
            - name: VITE_CHAT_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_CHAT_SERVICE_API_URL
            - name: VITE_HISTORY_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-service-config
                  key: VITE_HISTORY_SERVICE_API_URL
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: "35.247.181.203" # Reserved static IP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
