apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: gcr.io/cs3219-peerprep-440616/frontend-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: VITE_FIREBASE_API_KEY
              value: "AIzaSyB9UUF76Bz_9GmmylPRviSL_uxsFXfsaJI"
            - name: VITE_FIREBASE_AUTH_DOMAIN
              value: "cs3219-g21.firebaseapp.com"
            - name: VITE_FIREBASE_DATABASE_URL
              value: "https://cs3219-g21-default-rtdb.asia-southeast1.firebasedatabase.app"
            - name: VITE_FIREBASE_PROJECT_ID
              value: "cs3219-g21"
            - name: VITE_FIREBASE_STORAGE_BUCKET
              value: "cs3219-g21.appspot.com"
            - name: VITE_FIREBASE_MESSAGING_SENDER_ID
              value: "958024239459"
            - name: VITE_FIREBASE_APP_ID
              value: "1:958024239459:web:72f1c7396a441127d72b56"
            - name: VITE_FIREBASE_MEASUREMENT_ID
              value: "G-RWHNR4RB38"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: "35.247.181.203" # Reserved static IP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
