services:

  frontend-service:
    build: ./frontend-service
    ports:
      - 3000:3000
    depends_on:
      - question-service
      - user-service
    volumes:
      - ./frontend-service:/app
      - /app/node_modules

  question-service:
    build: ./question-service
    ports:
      - 8080:8080
    volumes:
      - ./question-service:/app
      - /app/node_modules

  user-service:
    build: ./user-service
    ports:
      - 3001:3001
    volumes:
      - ./user-service:/app
      - /app/node_modules

# Notes:
#
# Docker Compose will automatically create an internal network where services can resolve each other using their service names.
#
# For example, inside your frontend-service code, you can make requests to the question-service like this:
# - const questionServiceURL = "http://question-service:3001/api/questions";  # Hostname is the service name
