apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: gcr.io/cs3219-peerprep-440616/chat-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: USER_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: request-service-config
                  key: USER_SERVICE_API_URL
          resources:
            limits:
              cpu: "250m"
              memory: "500Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
  loadBalancerIP: "35.247.129.36"

---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: chat-service-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: chat-deployment
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50
