# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-deployment
  labels:
    app: history-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      containers:
        - name: history-service
          image: gcr.io/cs3219-peerprep-440616/history-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: history-service
spec:
  selector:
    app: history-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP
