apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-deployment
  labels:
    app: request-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-service
  template:
    metadata:
      labels:
        app: request-service
    spec:
      containers:
        - name: request-service
          image: gcr.io/cs3219-peerprep-440616/request-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: request-service
  namespace: default
spec:
  selector:
    app: request-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
