apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-deployment
  labels:
    app: request-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-service
  template:
    metadata:
      labels:
        app: request-service
    spec:
      containers:
        - name: request-service
          image: gcr.io/cs3219-peerprep-440616/request-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: USER_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: request-service-config
                  key: USER_SERVICE_API_URL
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: request-service
  namespace: default
spec:
  selector:
    app: request-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer
  loadBalancerIP: "34.87.78.127" # Reserved static IP

---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: request-service-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: request-deployment
#   minReplicas: 1
#   maxReplicas: 12
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50
