apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-deployment
  labels:
    app: room-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: room-service
          image: gcr.io/cs3219-peerprep-440616/room-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: room-service
spec:
  selector:
    app: room-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: room-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: room-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
