apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-deployment
  labels:
    app: room-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: room-service
          image: gcr.io/cs3219-peerprep-440616/room-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: room-service
spec:
  selector:
    app: room-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: ClusterIP
